- name: create an ubuntu instance on EC2
  hosts: localhost
  tasks:

  - name: start the instance
    ec2:
      image: ami-076bdd070268f9b8d 
      key_name: ansible
      region: eu-central-1 
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      instance_type: t2.nano
     # key_name: june20182
      # group: all-open
